### ISSUE TITLE
Pages needed

### ISSUE THREAD

**Issue by ciavashkh** [cloud-66-internal/help.cloud66.com#11]
- [x] MySQL(or Percona if configured via Manifest)
- [x] PostgreSQL
- [x] Redis
- [x] MongoDB
- [x] Elasticsearch
- [x] RabbitMQ
- [x] SQLite (only in development environments)
- [x] GlusterFS
- [x] InfluxDB
- [ ] Service.yml
- [ ] Manifest.yml
- [ ] Memcached
- [ ] Logrotate
- [ ] Logs
- [ ] Environment Variables
- [x] Normal SSL * Explaining how to set up SSL termination
- [x] Lets Encrypt * Explaining how to set up SSL termination
- [x] AWS
- [x] GoogleCloud
- [x] Linode
- [x] Azure
- [x] DigitalOcean
- [x] Rakspace
- [ ] LoadBalancer
- [ ] ELB  * Explaining how to set up SSL termination
- [ ] Custom Server
- [ ] Haproxy
- [ ] Filebeat * Explaining what endpoint is needed for Filebeat
- [ ] Logentries
- [ ] Applying upgrades

**Comment by dragospopa** [comment]
All of these are part of the new structure at this point.
