### ISSUE TITLE
Service.yml keys explanations are not structured in a well-defined way

### ISSUE THREAD

**Issue by dragospopa** [cloud-66-internal/help.cloud66.com#12]
At this point, service.yml is explained under a page called "Docker service configuration" and has, among others, a huge table with a fairly short definition for (more or less) each key that we support. The problem arises when a user wants to fing out more about one of the keys. They press on the name and are redirected to an entirely different part of the website, without any obvious relation with the previous service.yml article where they started from. 

Another issue is that the tags do not have a consistent explanation structure as most of them are grouped (groups of 2,4,7, etc) and usually tend to increase ambiguity as the user usually is interested in just the tag that he started from.

There is also another case that the user gets to one of the posts that explains one of these groups of service.yml tags without having any clue that it is actually referring to settings related to service.yml and not something they can easily set pressing a button in the UI.

**Possible solution:**
All the tags should either be explained in the same place (as in creating a API-style doc page for service.yml as well) or they should have an individual page that explains each of them (but this would be a good idea provided we can relate these pages very well - having a button to go directly to the main service.yml post or go to the other related keys that we use).

**Comment by khash** [comment]
Valid points. Both service.yml and manifest.yml should have dedicated and independent help pages not related to any other product. Parts of this document should be possible to inline in another document but with a link back to the main page (as per your last comment).
