### ISSUE TITLE
Manifest page does not mention how to use with Node

### ISSUE THREAD

**Issue by dragospopa** [cloud-66-internal/help.cloud66.com#13]
Our `Build your manifest file` is currently trying to be as specific as possible regarding how the `manifest.yaml` is supposed to work if you are either working with a Docker or a Rails stack. The issue is that at no point, the possibility of using the `manifest.yaml` with a Node stack is mentioned and, of course, how to do it.

Also, due to current updates, it would be great if we could mention not only how to use `manifest.yaml` with Docker stacks but with container stacks in general (as this might proove ambiguous to some users using K8s).

Content needs to be updated so that it would fit all products

**Comment by DuBistKomisch** [comment]
Yeah turns out you just need to use `node:` and the standard options seem to work. I only needed to set the `vpc_id` and `servers` so it was good enough. Docs definitely need work.

**Comment by khash** [comment]
Thank you @DuBistKomisch for your note and sorry for not responding sooner. We are renewing our documentation and will release a new version soon.

**Comment by DuBistKomisch** [comment]
@khash Thanks that's great, and related, is the `gateway:` option meant to work for node stacks, or only rails/docker? It didn't seem to do anything for me, but works fine on our rails stack. Probably worth mentioning in the docs if not.
