### ISSUE TITLE
Add a few pages under getting started category

### ISSUE THREAD

**Issue by ciavashkh** [cloud-66-internal/help.cloud66.com#25]
Under Getting started category we need 

- [ ] A brief explanation of what manifest.yml and its purpose are
- [ ] A brief explanation of what service.yml and its purpose are

**Comment by dragospopa** [comment]
The current pages for both Build your Manifest File and Docker service configuration to not offer enough insight for a new user that has never used either of them. This is why we need to create (for each of them) a post under the Getting Started category that would represent a short tutorial and presentation of what/how to do when you want to first gather knowledge regarding either of them.
