### ISSUE TITLE
Site index

### ISSUE THREAD

**Issue by ciavashkh** [cloud-66-internal/help.cloud66.com#26]
We need to create the Help site's index on the left side bar.

**Comment by dragospopa** [comment]
Found 2 solutions so far:

- using a hardcoded file under `/_data/sitemap.yml` to build the navigation menu or create a job to do that inside the stack automatically
- loop through all the front-matter(header) generated by jekyll using the site.documents and generated  the structure automatically (provided some filters and loops are used). The only issue is that if you print {{ for each doc in site.documets }} -> {{ doc.categories }} it will show the actual category of the page, but if used inside an if-statement as in {% if doc.categories == 'deployment' %} condition is never TRUE and doc.categories seems to always be empty (_INVESTIGATING_)

**Comment by dragospopa** [comment]
SOLVED using first option
