### ISSUE TITLE
Adding Tabs for product

### ISSUE THREAD

**Issue by ciavashkh** [cloud-66-internal/help.cloud66.com#29]
I think it'd be a good idea to have a tab on top that you can change product while you are on the page.

For instance: if you are looking at rails/manifest help page by changing the tab to Maestro it will show you maestro/manifest.

The fall back (404 for this specific case) would be a page saying that the page is not available for that product and user can navigate trough the new product tab using the navigation bar.

**Comment by dragospopa** [comment]
Solved - links will direct the user to the main page for each product, not the current page of the targeted product.
